### ISSUE TITLE
Can't view the entire page on mobile

### ISSUE THREAD

**Issue by saraspaudel** [maks112v/react-coming-soon#3]
#2 
Not resolved. 

The update didn't resolve the issue.

Device: iPhone X, Chrome, iOS 12.4

![unnamed](https://user-images.githubusercontent.com/13654369/62810921-44605b80-bac5-11e9-8098-4fccb0fb936c.png)

**Comment by maks112v** [comment]
Can you please send your full code.

**Comment by saraspaudel** [comment]
@maks112v https://github.com/saraspaudel/E-Code.org

**Comment by saraspaudel** [comment]
Updating to 1.0.6 fixes this issue. Thank you.
