### ISSUE TITLE
Can not create a config file

### ISSUE THREAD

**Issue by robpedersendev** [maks112v/react-coming-soon#4]
There is no way to create a config file and there are no instructions on how to create a config file

**Comment by maks112v** [comment]
You can generate a config on this page: [https://react-coming-soon.maksv.me/](https://react-coming-soon.maksv.me/)

**Comment by robpedersendev** [comment]
This gif shows that when I go to that page, it does  not allow me to create a config, just shows what the demo looks like, also the documentation on how to incorporate the config is also missing
![2019-12-01-15-42-42](https://user-images.githubusercontent.com/40696979/69921661-3dcd6980-1451-11ea-83ab-6d177a676266.gif)

**Comment by robpedersendev** [comment]
Why was this closed? 

You clearly cant make a config at that page.
